YOURLIB=YOURLIB

all :

	setccsid 1252 JAVARPGGSE.DSPF
	system "CRTSRCPF FILE($(YOURLIB)/QDDSSRC) RCDLEN(132) CCSID(37)"
	system "CPYFRMSTMF FROMSTMF('JAVARPGGSE.DSPF') TOMBR('/QSYS.lib/$(YOURLIB).lib/QDDSSRC.file/JAVARPGGSE.mbr') MBROPT(*REPLACE)"
	system "CRTDSPF file($(YOURLIB)/JAVARPGGSE) SRCFILE($(YOURLIB)/QDDSSRC)"


	system "CRTSRCPF FILE($(YOURLIB)/QRPGLESRC) RCDLEN(112) CCSID(1208)"
	setccsid 1252 JAVARPG.SQLRPGLE
	setccsid 1252 UTIL04PS.SQLRPGLE
	system "CPYFRMSTMF FROMSTMF('UTIL04PS.SQLRPGLE') TOMBR('/QSYS.lib/$(YOURLIB).lib/QRPGLESRC.file/UTIL04PS.mbr') MBROPT(*REPLACE)"

	system "CRTSQLRPGI OBJ($(YOURLIB)/JAVARPG) SRCSTMF('JAVARPG.SQLRPGLE') RPGPPOPT(*LVL2) COMPILEOPT('OPTION(*NOUNREF) DBGVIEW(*LIST)') DBGVIEW(*NONE) COMMIT(*NONE)"

